import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F9FAFB',
  },
  contentContainer: {
    paddingHorizontal: 16,
    paddingBottom: 24,
  },
  logoWrapper: {
    alignItems: 'center',
    marginBottom: 12,
  },
  logoText: {
    textAlign: 'center',
    fontSize: 16,
    fontWeight: '700',
    lineHeight: 18,
    color: '#7CCCB8',
    letterSpacing: 1,
  },
  profileCard: {
    borderRadius: 0,
    backgroundColor: '#0E2645',
    paddingHorizontal: 16,
    paddingVertical: 18,
    marginHorizontal: -16,
    marginBottom: 20,
    flexDirection: 'row',
    alignItems: 'center',
  },
  avatar: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#7C4DFF',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 16,
  },
  avatarText: {
    fontSize: 28,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  profileTextBlock: {
    flex: 1,
  },
  profileName: {
    fontSize: 22,
    fontWeight: '700',
    color: '#FFFFFF',
    marginBottom: 4,
  },
  profileMeta: {
    fontSize: 14,
    color: '#D6E7F8',
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#111827',
    marginBottom: 18,
  },
  filterRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    marginBottom: 18,
  },
  filterGroup: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    flex: 1,
  },
  filterLabel: {
    fontSize: 14,
    color: '#6B7280',
    marginRight: 10,
    marginBottom: 8,
  },
  filterButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingBottom: 8,
    borderBottomWidth: 2,
    borderBottomColor: '#58B7E3',
  },
  filterButtonText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#58B7E3',
    marginRight: 8,
  },
  filterChevron: {
    fontSize: 14,
    color: '#58B7E3',
    fontWeight: '700',
    marginTop: 1,
  },
  orderGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: 20,
  },
  orderLabel: {
    fontSize: 14,
    color: '#6B7280',
    marginRight: 10,
  },
  orderButton: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    alignItems: 'center',
    justifyContent: 'center',
  },
  orderButtonText: {
    fontSize: 20,
    fontWeight: '700',
    color: '#111827',
    lineHeight: 22,
  },
  sortMenu: {
    marginTop: -8,
    marginBottom: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    backgroundColor: '#FFFFFF',
    padding: 8,
    shadowColor: '#000000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.06,
    shadowRadius: 2,
    elevation: 2,
  },
  sortOption: {
    minHeight: 40,
    borderRadius: 4,
    justifyContent: 'center',
    paddingHorizontal: 12,
    marginBottom: 8,
    backgroundColor: '#F3F4F6',
  },
  sortOptionLast: {
    marginBottom: 0,
  },
  sortOptionSelected: {
    backgroundColor: '#58B7E3',
  },
  sortOptionText: {
    fontSize: 14,
    color: '#111827',
  },
  sortOptionTextSelected: {
    color: '#FFFFFF',
  },
  emptyStateCard: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    backgroundColor: '#FFFFFF',
    paddingVertical: 24,
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyStateTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#111827',
    marginBottom: 8,
  },
  emptyStateDescription: {
    fontSize: 14,
    lineHeight: 22,
    color: '#6B7280',
    textAlign: 'center',
  },
});

export default styles;
